# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lane_detection/lane_message.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class lane_message(genpy.Message):
  _md5sum = "37cb1739b1f69cba6b6996620377af4d"
  _type = "lane_detection/lane_message"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Boolean value, indicating whether the left lane is detected
uint8 flag_detected 

# Parameters of the left lane in the ground plane
int32 rho 
float32 theta 
"""
  __slots__ = ['flag_detected','rho','theta']
  _slot_types = ['uint8','int32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       flag_detected,rho,theta

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(lane_message, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.flag_detected is None:
        self.flag_detected = 0
      if self.rho is None:
        self.rho = 0
      if self.theta is None:
        self.theta = 0.
    else:
      self.flag_detected = 0
      self.rho = 0
      self.theta = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_Bif.pack(_x.flag_detected, _x.rho, _x.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.flag_detected, _x.rho, _x.theta,) = _struct_Bif.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_Bif.pack(_x.flag_detected, _x.rho, _x.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.flag_detected, _x.rho, _x.theta,) = _struct_Bif.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_Bif = struct.Struct("<Bif")
