// Generated by gencpp from file pev_msgs/DollyEncoderStamped.msg
// DO NOT EDIT!


#ifndef PEV_MSGS_MESSAGE_DOLLYENCODERSTAMPED_H
#define PEV_MSGS_MESSAGE_DOLLYENCODERSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pev_msgs
{
template <class ContainerAllocator>
struct DollyEncoderStamped_
{
  typedef DollyEncoderStamped_<ContainerAllocator> Type;

  DollyEncoderStamped_()
    : header()
    , left_encoder_count(0)
    , right_encoder_count(0)  {
    }
  DollyEncoderStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_encoder_count(0)
    , right_encoder_count(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _left_encoder_count_type;
  _left_encoder_count_type left_encoder_count;

   typedef int64_t _right_encoder_count_type;
  _right_encoder_count_type right_encoder_count;




  typedef boost::shared_ptr< ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> const> ConstPtr;

}; // struct DollyEncoderStamped_

typedef ::pev_msgs::DollyEncoderStamped_<std::allocator<void> > DollyEncoderStamped;

typedef boost::shared_ptr< ::pev_msgs::DollyEncoderStamped > DollyEncoderStampedPtr;
typedef boost::shared_ptr< ::pev_msgs::DollyEncoderStamped const> DollyEncoderStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pev_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'pev_msgs': ['/home/ubuntu/PEV/pev_ws/src/pev_highlevel/pev_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c71875162b1bc3e5def95095c752ad0";
  }

  static const char* value(const ::pev_msgs::DollyEncoderStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c71875162b1bc3eULL;
  static const uint64_t static_value2 = 0x5def95095c752ad0ULL;
};

template<class ContainerAllocator>
struct DataType< ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pev_msgs/DollyEncoderStamped";
  }

  static const char* value(const ::pev_msgs::DollyEncoderStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Time stamped left and right encoder turns and counts\n\
## If encoder counts is negative, the wheel has turned reverse with respect to start position\n\
\n\
std_msgs/Header header\n\
int64 left_encoder_count\n\
int64 right_encoder_count\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pev_msgs::DollyEncoderStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_encoder_count);
      stream.next(m.right_encoder_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DollyEncoderStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pev_msgs::DollyEncoderStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pev_msgs::DollyEncoderStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_encoder_count: ";
    Printer<int64_t>::stream(s, indent + "  ", v.left_encoder_count);
    s << indent << "right_encoder_count: ";
    Printer<int64_t>::stream(s, indent + "  ", v.right_encoder_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEV_MSGS_MESSAGE_DOLLYENCODERSTAMPED_H
