// Generated by gencpp from file pev_msgs/DriveCommandStamped.msg
// DO NOT EDIT!


#ifndef PEV_MSGS_MESSAGE_DRIVECOMMANDSTAMPED_H
#define PEV_MSGS_MESSAGE_DRIVECOMMANDSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <pev_msgs/DriveCommand.h>

namespace pev_msgs
{
template <class ContainerAllocator>
struct DriveCommandStamped_
{
  typedef DriveCommandStamped_<ContainerAllocator> Type;

  DriveCommandStamped_()
    : header()
    , drive()  {
    }
  DriveCommandStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , drive(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::pev_msgs::DriveCommand_<ContainerAllocator>  _drive_type;
  _drive_type drive;




  typedef boost::shared_ptr< ::pev_msgs::DriveCommandStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pev_msgs::DriveCommandStamped_<ContainerAllocator> const> ConstPtr;

}; // struct DriveCommandStamped_

typedef ::pev_msgs::DriveCommandStamped_<std::allocator<void> > DriveCommandStamped;

typedef boost::shared_ptr< ::pev_msgs::DriveCommandStamped > DriveCommandStampedPtr;
typedef boost::shared_ptr< ::pev_msgs::DriveCommandStamped const> DriveCommandStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pev_msgs::DriveCommandStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pev_msgs::DriveCommandStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pev_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'pev_msgs': ['/home/ubuntu/PEV/pev_ws/src/pev_highlevel/pev_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pev_msgs::DriveCommandStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pev_msgs::DriveCommandStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pev_msgs::DriveCommandStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pev_msgs::DriveCommandStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pev_msgs::DriveCommandStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pev_msgs::DriveCommandStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pev_msgs::DriveCommandStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1fd5d7f58889cefd44d29f6653240d0c";
  }

  static const char* value(const ::pev_msgs::DriveCommandStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1fd5d7f58889cefdULL;
  static const uint64_t static_value2 = 0x44d29f6653240d0cULL;
};

template<class ContainerAllocator>
struct DataType< ::pev_msgs::DriveCommandStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pev_msgs/DriveCommandStamped";
  }

  static const char* value(const ::pev_msgs::DriveCommandStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pev_msgs::DriveCommandStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Time stamped drive command for robots with Ackermann steering.\n\
#  $Id$\n\
\n\
Header        header\n\
DriveCommand  drive\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: pev_msgs/DriveCommand\n\
## Driving command for a car robot\n\
\n\
# Assumes Ackermann front-wheel steering. The left and right front\n\
# wheels are generally at different angles. To simplify, the commanded\n\
# angle corresponds to the yaw of a virtual wheel located at the\n\
# center of the front axle.  Positive yaw is to the left. \n\
#\n\
\n\
float32 steering_angle          # desired virtual angle (radians)\n\
float32 steering_angle_velocity # desired rate of change (radians/s)\n\
\n\
# Drive at requested speed, acceleration and jerk (the 1st, 2nd and\n\
# 3rd derivatives of position). All are measured at the vehicle's\n\
# center \n\
#\n\
\n\
float32 speed                   # desired forward speed (m/s)\n\
float32 acceleration            # desired acceleration (m/s^2)\n\
float32 jerk                    # desired jerk (m/s^3)\n\
";
  }

  static const char* value(const ::pev_msgs::DriveCommandStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pev_msgs::DriveCommandStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.drive);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveCommandStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pev_msgs::DriveCommandStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pev_msgs::DriveCommandStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "drive: ";
    s << std::endl;
    Printer< ::pev_msgs::DriveCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.drive);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEV_MSGS_MESSAGE_DRIVECOMMANDSTAMPED_H
